#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WercsTestWebForms.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LocalDB")]
	public partial class LocalDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertT_Language(T_Language instance);
    partial void UpdateT_Language(T_Language instance);
    partial void DeleteT_Language(T_Language instance);
    #endregion
		
		public LocalDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LocalDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LocalDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LocalDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LocalDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LocalDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<T_Language> T_Languages
		{
			get
			{
				return this.GetTable<T_Language>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Languages")]
	public partial class T_Language : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _F_Language;
		
		private string _F_Language_Name;
		
		private string _F_Codepage;
		
		private System.Nullable<System.DateTime> _F_Date_Stamp;
		
		private string _F_DATE_FORMAT;
		
		private string _F_User_Updated;
		
		private System.Nullable<float> _F_LCID;
		
		private System.Nullable<int> _F_Special_Handling;
		
		private System.Nullable<int> _F_Direction;
		
		private string _F_TRANSLATION_SOURCE;
		
		private string _F_RTF_ENCODING;
		
		private string _F_HTML_ENCODING;
		
		private string _F_RTF_CODEPAGE;
		
		private int _F_RTF_FONT_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnF_LanguageChanging(string value);
    partial void OnF_LanguageChanged();
    partial void OnF_Language_NameChanging(string value);
    partial void OnF_Language_NameChanged();
    partial void OnF_CodepageChanging(string value);
    partial void OnF_CodepageChanged();
    partial void OnF_Date_StampChanging(System.Nullable<System.DateTime> value);
    partial void OnF_Date_StampChanged();
    partial void OnF_DATE_FORMATChanging(string value);
    partial void OnF_DATE_FORMATChanged();
    partial void OnF_User_UpdatedChanging(string value);
    partial void OnF_User_UpdatedChanged();
    partial void OnF_LCIDChanging(System.Nullable<float> value);
    partial void OnF_LCIDChanged();
    partial void OnF_Special_HandlingChanging(System.Nullable<int> value);
    partial void OnF_Special_HandlingChanged();
    partial void OnF_DirectionChanging(System.Nullable<int> value);
    partial void OnF_DirectionChanged();
    partial void OnF_TRANSLATION_SOURCEChanging(string value);
    partial void OnF_TRANSLATION_SOURCEChanged();
    partial void OnF_RTF_ENCODINGChanging(string value);
    partial void OnF_RTF_ENCODINGChanged();
    partial void OnF_HTML_ENCODINGChanging(string value);
    partial void OnF_HTML_ENCODINGChanged();
    partial void OnF_RTF_CODEPAGEChanging(string value);
    partial void OnF_RTF_CODEPAGEChanged();
    partial void OnF_RTF_FONT_IDChanging(int value);
    partial void OnF_RTF_FONT_IDChanged();
    #endregion
		
		public T_Language()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Language", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string F_Language
		{
			get
			{
				return this._F_Language;
			}
			set
			{
				if ((this._F_Language != value))
				{
					this.OnF_LanguageChanging(value);
					this.SendPropertyChanging();
					this._F_Language = value;
					this.SendPropertyChanged("F_Language");
					this.OnF_LanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Language_Name", DbType="VarChar(20)")]
		public string F_Language_Name
		{
			get
			{
				return this._F_Language_Name;
			}
			set
			{
				if ((this._F_Language_Name != value))
				{
					this.OnF_Language_NameChanging(value);
					this.SendPropertyChanging();
					this._F_Language_Name = value;
					this.SendPropertyChanged("F_Language_Name");
					this.OnF_Language_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Codepage", DbType="VarChar(5)")]
		public string F_Codepage
		{
			get
			{
				return this._F_Codepage;
			}
			set
			{
				if ((this._F_Codepage != value))
				{
					this.OnF_CodepageChanging(value);
					this.SendPropertyChanging();
					this._F_Codepage = value;
					this.SendPropertyChanged("F_Codepage");
					this.OnF_CodepageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Date_Stamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> F_Date_Stamp
		{
			get
			{
				return this._F_Date_Stamp;
			}
			set
			{
				if ((this._F_Date_Stamp != value))
				{
					this.OnF_Date_StampChanging(value);
					this.SendPropertyChanging();
					this._F_Date_Stamp = value;
					this.SendPropertyChanged("F_Date_Stamp");
					this.OnF_Date_StampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_DATE_FORMAT", DbType="VarChar(25)")]
		public string F_DATE_FORMAT
		{
			get
			{
				return this._F_DATE_FORMAT;
			}
			set
			{
				if ((this._F_DATE_FORMAT != value))
				{
					this.OnF_DATE_FORMATChanging(value);
					this.SendPropertyChanging();
					this._F_DATE_FORMAT = value;
					this.SendPropertyChanged("F_DATE_FORMAT");
					this.OnF_DATE_FORMATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_User_Updated", DbType="VarChar(15)")]
		public string F_User_Updated
		{
			get
			{
				return this._F_User_Updated;
			}
			set
			{
				if ((this._F_User_Updated != value))
				{
					this.OnF_User_UpdatedChanging(value);
					this.SendPropertyChanging();
					this._F_User_Updated = value;
					this.SendPropertyChanged("F_User_Updated");
					this.OnF_User_UpdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_LCID", DbType="Real")]
		public System.Nullable<float> F_LCID
		{
			get
			{
				return this._F_LCID;
			}
			set
			{
				if ((this._F_LCID != value))
				{
					this.OnF_LCIDChanging(value);
					this.SendPropertyChanging();
					this._F_LCID = value;
					this.SendPropertyChanged("F_LCID");
					this.OnF_LCIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Special_Handling", DbType="Int")]
		public System.Nullable<int> F_Special_Handling
		{
			get
			{
				return this._F_Special_Handling;
			}
			set
			{
				if ((this._F_Special_Handling != value))
				{
					this.OnF_Special_HandlingChanging(value);
					this.SendPropertyChanging();
					this._F_Special_Handling = value;
					this.SendPropertyChanged("F_Special_Handling");
					this.OnF_Special_HandlingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Direction", DbType="Int")]
		public System.Nullable<int> F_Direction
		{
			get
			{
				return this._F_Direction;
			}
			set
			{
				if ((this._F_Direction != value))
				{
					this.OnF_DirectionChanging(value);
					this.SendPropertyChanging();
					this._F_Direction = value;
					this.SendPropertyChanged("F_Direction");
					this.OnF_DirectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_TRANSLATION_SOURCE", DbType="VarChar(255)")]
		public string F_TRANSLATION_SOURCE
		{
			get
			{
				return this._F_TRANSLATION_SOURCE;
			}
			set
			{
				if ((this._F_TRANSLATION_SOURCE != value))
				{
					this.OnF_TRANSLATION_SOURCEChanging(value);
					this.SendPropertyChanging();
					this._F_TRANSLATION_SOURCE = value;
					this.SendPropertyChanged("F_TRANSLATION_SOURCE");
					this.OnF_TRANSLATION_SOURCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_RTF_ENCODING", DbType="VarChar(50)")]
		public string F_RTF_ENCODING
		{
			get
			{
				return this._F_RTF_ENCODING;
			}
			set
			{
				if ((this._F_RTF_ENCODING != value))
				{
					this.OnF_RTF_ENCODINGChanging(value);
					this.SendPropertyChanging();
					this._F_RTF_ENCODING = value;
					this.SendPropertyChanged("F_RTF_ENCODING");
					this.OnF_RTF_ENCODINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_HTML_ENCODING", DbType="VarChar(50)")]
		public string F_HTML_ENCODING
		{
			get
			{
				return this._F_HTML_ENCODING;
			}
			set
			{
				if ((this._F_HTML_ENCODING != value))
				{
					this.OnF_HTML_ENCODINGChanging(value);
					this.SendPropertyChanging();
					this._F_HTML_ENCODING = value;
					this.SendPropertyChanged("F_HTML_ENCODING");
					this.OnF_HTML_ENCODINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_RTF_CODEPAGE", DbType="VarChar(15)")]
		public string F_RTF_CODEPAGE
		{
			get
			{
				return this._F_RTF_CODEPAGE;
			}
			set
			{
				if ((this._F_RTF_CODEPAGE != value))
				{
					this.OnF_RTF_CODEPAGEChanging(value);
					this.SendPropertyChanging();
					this._F_RTF_CODEPAGE = value;
					this.SendPropertyChanged("F_RTF_CODEPAGE");
					this.OnF_RTF_CODEPAGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_RTF_FONT_ID", DbType="Int NOT NULL")]
		public int F_RTF_FONT_ID
		{
			get
			{
				return this._F_RTF_FONT_ID;
			}
			set
			{
				if ((this._F_RTF_FONT_ID != value))
				{
					this.OnF_RTF_FONT_IDChanging(value);
					this.SendPropertyChanging();
					this._F_RTF_FONT_ID = value;
					this.SendPropertyChanged("F_RTF_FONT_ID");
					this.OnF_RTF_FONT_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
